apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: uploader
  name: uploader
spec:
  replicas: 2
  selector:
    matchLabels:
      run: uploader
  template:
      metadata:
        labels:
            run: uploader
      spec:
          containers:
            - image: hiroyha/uploader:version-0.0.7
              name: uploader
              env:
              - name: STORAGE_CONNECTION_STRING
                value: "DefaultEndpointsProtocol=https;AccountName=saahonhd;AccountKey=iVN6ltARtkb1S2JTQR1pAJx+zOXVcv7CRjcH0kMN/YNMeyrMtkXPL31uoJ8jw6aN3nmiqY9aGjuAUW7GqBIsQA==;EndpointSuffix=core.windows.net"
              - name: STORAGE_CONTAINER_NAME
                value: "container"
              - name: DATABASE_URL
                value: "jdbc:sqlserver://sqldbahonhd.database.windows.net:1433;database=aksdemo;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;"
              - name: DATABASE_USERNAME
                value: "sqladmin"
              - name: DATABASE_PASSWORD
                value: "Password1!"
              - name: SERVER_PORT
                value: "80"
              - name: APPLICATIONINSIGHTS_CONNECTION_STRING
                value: "InstrumentationKey=740cd0a6-74a2-45da-bb1b-ca7a66fe9828;IngestionEndpoint=https://southeastasia-0.in.applicationinsights.azure.com/"
              readinessProbe:
                tcpSocket:
                  port: 80
                initialDelaySeconds: 120
                periodSeconds: 5
              livenessProbe:
                tcpSocket:
                  port: 80
                initialDelaySeconds: 120
                periodSeconds: 5
              resources:
                requests:
                  memory: "512Mi"
                  cpu: "500m"
                limits:
                  memory: "512Mi"
                  cpu: "500m" 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: uploader
  name: uploader
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: uploader
  type: LoadBalancer
